### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by grndvl1** [techprd/kotlin_node_js_seed#2]
Followed directions and when I start the module I get this "silly lifecycle kotlin_node_js@1.0.0~start: Returned: code: 1  signal: null"

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kotlin_node_js@1.0.0~prestart: kotlin_node_js@1.0.0
6 info lifecycle kotlin_node_js@1.0.0~start: kotlin_node_js@1.0.0
7 verbose lifecycle kotlin_node_js@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle kotlin_node_js@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\NodeJsInstalls\kotlin_node_js_seed\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter\Driver;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\jmatthews\AppData\Local\Android\sdk\platform-tools;C:\Program Files\Java\jdk1.8.0_121;C:\Users\jmatthews\AppData\Roaming\npm
9 verbose lifecycle kotlin_node_js@1.0.0~start: CWD: C:\NodeJsInstalls\kotlin_node_js_seed
10 silly lifecycle kotlin_node_js@1.0.0~start: Args: [ '/d /s /c', './gradlew build; node backend/server/app.js' ]
11 silly lifecycle kotlin_node_js@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle kotlin_node_js@1.0.0~start: Failed to exec start script
13 verbose stack Error: kotlin_node_js@1.0.0 start: `./gradlew build; node backend/server/app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid kotlin_node_js@1.0.0
15 verbose cwd C:\NodeJsInstalls\kotlin_node_js_seed
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error kotlin_node_js@1.0.0 start: `./gradlew build; node backend/server/app.js`
22 error Exit status 1
23 error Failed at the kotlin_node_js@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by techprd** [comment]
sorry on windows the run command is little different.
so this ./gradlew build; node backend/server/app.js doesn't work for you

use following instead:
cd to project

npm install

**for CMD use:**
gradlew.bat build

**for powershell use:**
.\gradlew.bat build

**then run the server:**
node backend/server/app.js
